---
title: "Cluster analysis"
output: html_notebook
---

Set Session -> Set Working Directory -> To Source File Location

Pre requisite packages. 
````{r setup}

library(tidyr)
library(pvclust)
library(ComplexHeatmap)
library(dendextend)

```

Load the final summary file
```{r}

    df <- 
    read.csv('../outputs/Barcode/summaryFileTestV3.csv',
             stringsAsFactors = FALSE,
             header = TRUE)

```


Get rid of epinephrine and U44619
```{r}

df <- subset(df, agonist != "epinephrine")
df <- subset(df, agonist != "U46619")
df <- df[,c("donor","output","agonist","Sensitivity","Capacity")]

print(head(df))

```

Reshape the data
```{r}
   
    df.long <- gather(df,
                      desc,
                      metric,
                      c("Sensitivity","Capacity"))
 
    df.long$measure <- paste(df.long$output,df.long$agonist,df.long$desc,sep="_")
    df.long <- df.long[,c("donor","measure","metric")]
    
     df.wide <- spread(df.long, 
                       measure, 
                       metric)
     
     df.wide <- df.wide %>% drop_na()


```

Cluster variables and check if they are stable
```{r  fig.height=6, fig.width=8}  

pvc <- pvclust((df.wide[,c(-1)]), 
               method.dist="manhattan", 
               method.hclust="ward.D2", 
               nboot = 500)
                  
plot(pvc, hang = -1, cex = 0.5)
pvrect(pvc)

```

```{r}  

#png(
# filename = "FigDendogramColumn.png",
# width = 16,
# height = 5,
# units = 'cm',
# res = 400
#)

par(mar=c(2.1, 3.1, 2.1, 1.1), mgp=c(3, 1, 0), las=0)

plot(pvc, 
      hang = -1, 
      cex = 0.01, 
      cex.pv=0.7, 
      lwd=2, 
      main="", 
      float=0.03,
      print.num = FALSE,
      sub="",
      xlab=""
 )   
#pvrect(pvc)

#dev.off()

```

Cluster the rows and check if the clusters are stable
```{r}  

mat <- t(as.matrix(df.wide[,c(-1)]))

pvr <- pvclust(mat, 
               method.dist="euclidean", 
               method.hclust="complete", 
               nboot = 1000)

```

Create a plot of the row clusters
```{r}

# png(
#   filename = "FigDendogramRows.png",
#   width = 25,
#   height = 6,
#   units = 'cm',
#   res = 400
# )
par(mar = c(2.1, 3.1, 2.1, 1.1),
    mgp = c(3, 1, 0),
    las = 0)

as.dendrogram(pvr) %>% set(
  "branches_k_color",
  value = c(
    "coral1",
    "goldenrod1",
    "seagreen3",
    "dodgerblue",
    "darkolivegreen4",
    "darkgoldenrod3"
  ),
  k = 6
) %>% set("labels_cex", 0.1) %>% set("branches_lwd", 3) %>% plot(main = "donor labelling")
pvr %>% text(
  print.pv = FALSE,
  print.num = FALSE,
  cex = 0.5,
  float = 0.02,
  col = c("red", "black")
)

#dev.off()

```

Generate the heatmap
```{r   fig.height=8, fig.width=5}  

# png(
#   filename = "FigHeatmap.png",
#   width = 18,
#   height = 25,
#   units = 'cm',
#   res = 400
# )

df.rownames = as.matrix(df.wide[, c(1)])
df.colnames = as.matrix(names(df.wide)[c(-1)])
df.colnames <- gsub("_", "\n", df.colnames)

heattop <- HeatmapAnnotation(
  text = anno_text(
    df.colnames[, 1],
    rot = 90,
    just = "left",
    gp = gpar(
      fontsize = 8,
      direction = "horizontal",
      lineheight =
        0.75
    )
    ,
    location = unit(3, "mm")
  ),
  height = unit(2, "cm")
)


ht <- Heatmap(
  as.matrix(df.wide[, c(-1)]),
  cluster_columns = pvc$hclust,
  cluster_rows = as.dendrogram(pvr),
  split = 6,
  left_annotation = rowAnnotation(foo = anno_block(gp = gpar(
    fill = c(
      "coral1",
      "goldenrod1",
      "seagreen3",
      "dodgerblue",
      "darkolivegreen4",
      "darkgoldenrod3"
    )
  ))),
  show_row_dend = FALSE,
  show_column_dend = FALSE,
  top_annotation = heattop,
  show_column_names = FALSE,
  show_heatmap_legend = FALSE
)

#place donor numbers to the right
r1 <- rowAnnotation(
  names = row_anno_text(
    x = paste(df.rownames[, 1]),
    just = "left",
    offset = 0,
    gp = gpar(fontsize = 8)
  ),
  width = unit(2, "cm")
)

ht_list <-
  draw(ht + r1)

print(ht_list)

#dev.off()

```

